spring.application.name=playground-basic
spring.cache.type=simple
spring.cache.jcache.config=classpath:ehcache.xml
app.baseUrl=http://hapi.fhir.org/baseR4
app.sleepTime=5000
app.patientFilePath=src/main/resources/patientNames.txt
app.inMemoryCacheEnable=false